version: '2.1'

services: 
  vidly:
    build: .
    volumes:
    - .:/usr/src/app
    ports:
    - 3001:3000
    - 8001:8001
    environment:
      sapiens_jwtPrivateKey: casa
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports: 
      - 4001:27017
