version: '2.1'

services: 
  vidly:
    build: ./sapiens
    volumes:
    - ./sapiens:/usr/src/app
    ports:
    - 3001:3000
    - 8001:8001
    environment:
      sapiens_jwtPrivateKey: casa
    depends_on:
      - mongo
    labels:
      io.rancher.scheduler.affinity:host_label: key1=par1

  mongo:
    image: mongo
    ports: 
      - 4001:27017
    labels:
      io.rancher.scheduler.affinity:host_label: key1=par1
