version: '2.1'

services: 
  vidly:
    build: ./sapiens
    volumes:
    - ./sapiens:/usr/src/app
    ports:
    - 5001:3000
    environment:
      sapiens_jwtPrivateKey: casa
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports: 
      - 27018:27017
